default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: sb
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: expenze_development

test:
  <<: *default
  database: expenze

production:
  <<: *default
  database: expenze_production
